name: ElytraToggle
version: '1.0.1-SNAPSHOT'
main: com.github.cedricrev.elytratoggle.ElytraTogglePlugin
api-version: '1.21'
description: Simple bukkit plugin that toggles elytra midflight using jump key, just like in bedrock.
dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  elytratoggle.use:
    description: Allows toggling elytra mid-flight
    default: true