name: ElytraToggle
version: '1.0.1-SNAPSHOT'
main: com.github.cedricrev.elytratoggle.ElytraTogglePlugin
api-version: '1.21'
author: CedricRev
description: Simple bukkit plugin that toggles elytra midflight using jump key, just like in bedrock.
website: https://github.com/CedricRev
depends: [ packetevents ]
permissions:
  elytratoggle.use:
    description: Allows toggling elytra mid-flight
    default: true